### ISSUE TITLE
Test::PostgreSQL doesn't work out of the box as root any more

### ISSUE THREAD

**Issue by colinnewell** [TJC/Test-postgresql#16]
The releases this year don't appear to work when run as root.  pg_ctl doesn't seem to like being run directly as root.  If I set pg_ctl to '' when initialising Test::PostgreSQL it does work as it used to.

```
t/00-base.t .......... ok   
t/01-raii.t .......... pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
t/01-raii.t .......... skipped: /usr/lib/postgresql/9.4/bin/pg_ctl init -s -D /tmp/pgtest.L08S5/data -o -U postgres -A trust  failed:256 at /root/.cpanm/work/1455369474.1300/Test-PostgreSQL-1.20/blib/lib/Test/PostgreSQL.pm line 451.
t/02-multi.t ......... pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
t/02-multi.t ......... skipped: /usr/lib/postgresql/9.4/bin/pg_ctl init -s -D /tmp/pgtest.TdkqV/data -o -U postgres -A trust  failed:256 at /root/.cpanm/work/1455369474.1300/Test-PostgreSQL-1.20/blib/lib/Test/PostgreSQL.pm line 451.
t/04-multiprocess.t .. pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
t/04-multiprocess.t .. skipped: /usr/lib/postgresql/9.4/bin/pg_ctl init -s -D /tmp/pgtest.qu9me/data -o -U postgres -A trust  failed:256 at /root/.cpanm/work/1455369474.1300/Test-PostgreSQL-1.20/blib/lib/Test/PostgreSQL.pm line 451.
t/deadlock.t ......... pg_ctl: cannot be run as root
Please log in (using, e.g., "su") as the (unprivileged) user that will
own the server process.
t/deadlock.t ......... skipped: /usr/lib/postgresql/9.4/bin/pg_ctl init -s -D /tmp/pgtest.tY50R/data -o -U postgres -A trust  failed:256 at /root/.cpanm/work/1455369474.1300/Test-PostgreSQL-1.20/blib/lib/Test/PostgreSQL.pm line 451.

```

**Comment by TJC** [comment]
I know this might be controversial, but.. can you just run the tests as a user other than root?  
It doesn't strike me as good practice to be running random unit tests from the internet as the root user on your systems.

Although I recognise that with the advent of Docker, it's a lot more common to be running as a virtual-root user inside a Container. Unfortunately, the fact that pg_ctl refuses to run as root is a decision made upstream by the Postgresql devs.

Yes, you can get things to work by setting pg_ctl to '' and entering the backwards-compatibility codepath in Test-Postgres but this is not recommended.

**Comment by colinnewell** [comment]
That's not an entirely unreasonable position.  It's docker that is really where the problem comes in.  You generally don't switch users in containers so using the --sudo flag on cpanm to allow the tests to run as a regular user and then just use root to install the modules doesn't seem applicable.

Feel free to close this as won't fix if you don't want to change this on your end.  My apologies for creating the double issues, it can be tricky knowing where people will get notified (and sometimes it's just down to timing).

**Comment by TJC** [comment]
The advantages of RT are that co-maintainers may see issues in the future if/when they take over the project.

I do prefer Github myself.

**Comment by TJC** [comment]
I'm happy to keep this issue open so that it's visible in the future; but I don't have any immediate plans to fix it.

**Comment by colinnewell** [comment]
In that case it probably does make sense to close it as won't fix.  People will still be able to google it.  You can always add a proviso that patches are welcome if it's just a case that you don't want to invest the time.

**Comment by pjlsergeant** [comment]
This issue prevents the module being installed sensibly under Docker

**Comment by pjlsergeant** [comment]
How about an ENV variable that allows for random prefixes to be inserted in front of `pg_ctl`?

**Comment by TJC** [comment]
I think we'd be better off coming up with a solution that works for people in Docker, without requiring knowledge of special ENV vars.

There's actually some code in there that's supposed to detect running as root, and to then use setuid to nobody -- but under Docker, $USER seems to be undefined, so that codepath isn't firing.

**Comment by pjlsergeant** [comment]
> There's actually some code in there that's supposed to detect running as root, and to then use setuid to nobody

In which case, I think all that's needed is a doc patch to suggest this is explicitly set, with the error so it's easily Googleable :-)

**Comment by TJC** [comment]
Ah, I don't know.. I like stuff to be foolproof where possible.
I reckon replacing the $ENV{USER} check with a getuid could be better.. I'll  try something now

**Comment by TJC** [comment]
Could you two please test the latest master branch, or the 1.21_01 dev release on cpan, for me?

**Comment by pjlsergeant** [comment]
I *think* this is working, but I am having a completely unrelated issue with Alpine Linux and locales now :-D

**Comment by pjlsergeant** [comment]
Works On My Machine. Thanks buddy

**Comment by colinnewell** [comment]
That works for me too thanks.

**Comment by TJC** [comment]
Releasing as version 1.21.
