### ISSUE TITLE
Postgres shuts down too fast for Test::PostgreSQL

### ISSUE THREAD

**Issue by dracos** [TJC/Test-postgresql#21]
When I use Test::PostgreSQL 1.24, I get the "Pg refused to die gracefully; killing it violently." and "Pg really didn't die.. WTF?" messages, although the database has been shut down.

This is because the database process has already gone after the `kill $sig, $self->pid;` line but before the first `waitpid` call, which then returns -1, because there is no such PID. As I understand it, this loop (and the one a bit further down) should only be checking for equal to 0, not less than 0, because less than 0 means its job is done, the process is gone.

**Comment by TJC** [comment]
Thanks for reporting this -- I saw your PR too, but haven't had enough time this week to test it properly.
