### ISSUE TITLE
Fixed psql args version not released yet

### ISSUE THREAD

**Issue by pjlsergeant** [TJC/Test-postgresql#32]
https://github.com/TJC/Test-postgresql/commit/12616286c126ad511bee6aa3d3ce7f9c895938f7?_pjax=%23js-repo-pjax-container

This seems to deal with `-b` not being an allowable option on earlier Postgres. Please could someone release this version?

**Comment by TJC** [comment]
Ah, I think we were waiting (at the time) for another PR to go in, before the release.
That PR seems to have been stalled for a long time, so I think you've prompted us to get a new release out now.

**Comment by TJC** [comment]
New release is up.

Took a few tries, PAUSE or CPAN seems flakey today, giving lots of auth errors that go away on retries :/

I don't really work with Perl any more, so I hope some people can test this release out for me.

**Comment by TJC** [comment]
Argh, new release is failing on CPAN Testers
