### ISSUE TITLE
Needs new maintainer(s)

### ISSUE THREAD

**Issue by TJC** [TJC/Test-postgresql#35]
I haven't been working with Perl for a while, and so I'm not the best possible maintainer for this distribution.
For day-to-day issue management and releases, I'd like someone, or some people, to step up and take over.
(I'm happy to stay as a co-maintainer and answer requests for feedback, and even come back in the case of new maintainers departing if that's what it takes to keep the module alive.)

If you're interested in this position, please comment below, and if you have opinions about this process or how we should manage this, also, please comment below.

The way I imagine this happening is that we have several people with admin rights on the repository, and COMAINT or OWNER status on CPAN. Maintainers would create a pull-request to make a new release, and try to get at least one other maintainer to approve it before sending to CPAN.

**Comment by jjn1056** [comment]
As in the email conversation I am willing to step into this unless there is someone that already wanted it and has first dibs :)

**Comment by TJC** [comment]
@nohuhu and @SysPete -- you've been contributors in recent years -- I'd like to hear your thoughts.

(And apologies if I'm missing other major contributors; it's not intentional, just a sign that I'm spread over many fronts currently)

**Comment by SysPete** [comment]
@TJC I'd be very happy to see @jjn1056 take FIRST_COME in PAUSE. Sadly I haven't had a lot of time for this module but I am involved in a number of non-work projects that have a dep on it so am still interested in helping how I can.

**Comment by nohuhu** [comment]
@TJC Apologies for the late reply, last week was a bit crazy.

I'm also using this module in personal projects and would like to keep it chuggling. In fact I like this module so much that I ported it to JavaScript to use in other personal projects: [test-pg-pool](https://www.npmjs.com/package/test-pg-pool). :)

@jjn1056 wearing the primary maintainer hat is totally fine with me.

**Comment by TJC** [comment]
Excellent. Seems like it's decided then :)

**Comment by TJC** [comment]
I've made @jjn1056 primary owner of this distribution's namespace on CPAN.

I'm happy with @nohuhu being a co-maint, but didn't add them first before transferring ownership because I didn't think that through.
