### ISSUE TITLE
Released version 1.29 is borked?

### ISSUE THREAD

**Issue by nohuhu** [TJC/Test-postgresql#43]
It's been a while since I touched Perl for the last time, and it looks like I did something wrong while trying to release version 1.29. It does show up under my CPAN account (for some reason) but when I'm trying to install it with `cpanm` it grabs the previous version 1.28.

@TJC Could you fix that by cutting yet another release under your account please?

**Comment by TJC** [comment]
I had to build a whole new Perl toolchain (new laptop) but I think I've uploaded 1.29 to CPAN properly now.

Do you mind confirming that it looks good to you?

**Comment by nohuhu** [comment]
Yeah, same here: had to set up a new VM just to build, test, and release... Looks good on my end, thanks Toby!

**Comment by cole-h** [comment]
Thanks again!
